### ISSUE TITLE
Research valid values of `format` that were *removed* across dialects

### ISSUE THREAD

**Issue by jviotti** [json-schema-org/upgrade-downgrade-rules#1]

**Comment by Era-cell** [comment]
I have included each and every change for the "format" attribute. It has 4-5 pages so I will be providing the link:
https://docs.google.com/document/d/1x16V4UC6jj3lZoHovsFqpeBckQHSUTH-UHCgWc1I8qo/edit
Conventions used are:
"+" - format added
"-" - this format removed
"{keyword}:" - rfc/logic for the format changed
"-->" - indicating before and after

Briefly telling only about the changes in assertion and annotations:
draft0 to draft2 - says not required to validate. Which means annotation by default
draft 3 - MAY validate. So, can be assertion or annotation by default
draft 4 to draft 7 - Assertion by default, SHOULD provide annotation support.
2019-09 to 2020-12 - Annotations by default, SHOULD provide support for assertion.  

One question on this, which I didn't understand:
https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-01#section-7.2.3
what does it mean by peer implementation here?

**Comment by jviotti** [comment]
@Era-cell Great research! 

> It has 4-5 pages so I will be providing the link

What about sending a PR to include that document in this repo, as markdown file? I think it will be great to keep it here for posterity. Maybe as `research/formats.markdown`? 

> One question on this, which I didn't understand: https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-01#section-7.2.3 what does it mean by peer implementation here?

That paragraph is touching on the problem of two systems using JSON Schema to communicate. Because they may potentially be using different JSON Schema implementations, each of the systems refer to the JSON Schema implementation the other one is using as a "peer implementation".

**Comment by jviotti** [comment]
Maybe we should follow the markdown approach even for the conditions DSL research, etc. I'm thinking keeping it all in markdown under version control would be great. Let's try it out with this one and then we see?

**Comment by jviotti** [comment]
Other than that, reading through the document, is all seems manageable to me. We can always replace removed formats with i.e. `pattern` if needed

**Comment by Era-cell** [comment]
Okay, cool! I got all that. Lets try markdown
