### ISSUE TITLE
Research whether there was any change in annotations reported by official keywords across 2019-09 and 2020-12

### ISSUE THREAD

**Issue by jviotti** [json-schema-org/upgrade-downgrade-rules#3]

**Comment by Era-cell** [comment]
@jviotti most of annotation collection behavior remains the same for all of the keywords:
  for items, additionalItems, contains, properties, additionalProperties, .. even for unevaluated*
  2019 says:  Annotation results for "{keyword}" keywords from multiple schemas applied to the same instance location are combined by taking the union of the sets.
  2020 doesn't explicitly specify that
  
  Also importantly:
  2019 says: Unknown keywords SHOULD be ignored.
  But 2020: Unknown keywords SHOULD be treated as annotations, where the value of the keyword is the value of the annotation.
  -- that's all I found.. after much research

**Comment by jviotti** [comment]
Awesome work @Era-cell ! I think its OK. Nothing that seems to affect the upgrader
